Repository IBM/ibm-management-ingress-operator, pull requests merged in 2020-10, with the labels that each got.

#120 Fix failing testing jobs.
  build/health_check.sh
  cmd/manager/main.go
  common/config/.golangci.yml
  go.mod
  go.sum
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/operator/v1alpha1/managementingress_types.go
  pkg/controller/managementingress/handler/cert.go
  pkg/controller/managementingress/handler/cert_test.go
  pkg/controller/managementingress/handler/configmap.go
  pkg/controller/managementingress/handler/constants.go
  pkg/controller/managementingress/handler/default.go
  pkg/controller/managementingress/handler/deployment.go
  pkg/controller/managementingress/handler/ingressrequest.go
  pkg/controller/managementingress/handler/rbac.go
  pkg/controller/managementingress/handler/reconciler.go
  pkg/controller/managementingress/handler/route.go
  pkg/controller/managementingress/handler/scc.go
  pkg/controller/managementingress/handler/service.go
  pkg/controller/managementingress/handler/serviceaccount.go
  pkg/controller/managementingress/managementingress_controller.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/config/constants.go
  test/e2e/main_test.go
  test/e2e/managementingressoperatorset_test.go
  test/helpers/helpers.go
  test/testgroups/commonservice.go
  test/testsuits/managementingressoperatorset.go
Labels: lgtm, size/XXL

#122 add OWNER file.
  OWNERS
Labels: size/XS

#121 add gitignore file.
  .gitignore
Labels: approved, lgtm, size/S

#124 use restricted scc for management-ingress
  pkg/controller/managementingress/handler/configmap.go
  pkg/controller/managementingress/handler/constants.go
  pkg/controller/managementingress/handler/deployment.go
  pkg/controller/managementingress/handler/route.go
  pkg/controller/managementingress/handler/service.go
Labels: approved, lgtm, size/M

#126 use restricted scc.
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/ibm-management-ingress-operator.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#123 Optimize the permission for management-ingress operator and operand.
  cmd/manager/main.go
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/ibm-management-ingress-operator.v1.4.0.clusterserviceversion.yaml
  pkg/controller/managementingress/handler/common.go
  pkg/controller/managementingress/handler/configmap.go
  pkg/controller/managementingress/handler/deployment.go
  pkg/controller/managementingress/handler/route.go
Labels: approved, lgtm, size/L

#127 revert service port.
  pkg/controller/managementingress/handler/configmap.go
  pkg/controller/managementingress/handler/constants.go
  pkg/controller/managementingress/handler/route.go
  pkg/controller/managementingress/handler/service.go
Labels: approved, lgtm, size/S

#128 switch to issuer to create certificate.
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/ibm-management-ingress-operator.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#129 update operand image digest.
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/ibm-management-ingress-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#130 Create cp-proxy route
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/controller/managementingress/handler/configmap.go
  pkg/controller/managementingress/handler/constants.go
  pkg/controller/managementingress/handler/deployment.go
  pkg/controller/managementingress/handler/route.go
Labels: approved, lgtm, size/L

#132 Update owner reference of cp-proxy route
  cmd/manager/main.go
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/ibm-management-ingress-operator.v1.4.0.clusterserviceversion.yaml
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/controller/managementingress/handler/cert.go
  pkg/controller/managementingress/handler/configmap.go
  pkg/controller/managementingress/handler/deployment.go
  pkg/controller/managementingress/handler/route.go
  pkg/controller/managementingress/handler/service.go
  pkg/controller/managementingress/managementingress_controller.go
Labels: approved, size/L

#133 Fix build problem
  bundle/manifests/operator.ibm.com_managementingresses.yaml
Labels: approved, size/XS

#134 update bundle.
  Makefile
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_managementingresses.yaml
  config/crd/bases/operator.ibm.com_managementingresses.yaml
Labels: approved, lgtm, size/M

#136 update operand image digest.
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/ibm-management-ingress-operator.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#135 introduce filtered cache to optimize memory usage.
  controllers/handler/route.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/M
