Repository IBM/ibm-management-ingress-operator, pull requests merged in 2020-12, with the labels that each got.

#162 update operand imae digest.
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.2/ibm-management-ingress-operator.v1.4.2.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#164 [Wait] Fix issue cp-proxy route was not created in upgrade case
  controllers/handler/constants.go
  controllers/handler/reconciler.go
  controllers/handler/route.go
Labels: approved, do-not-merge/hold, size/L

#165 update the package file to trigger prow build
  deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
Labels: lgtm, size/XS
