Repository IBM/ibm-management-ingress-operator, pull requests merged in 2020-06, with the labels that each got.

#77 Move new version 1.2.1 to beta channel
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.1/ibm-management-ingress-operator.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
Labels: needs-ok-to-test, size/XS

#79 Move CSV 1.2.1 to stable channel
  deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
Labels: lgtm, needs-ok-to-test, size/XS

#78 Rebase from release-1.2.0 branch
  Makefile
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.1/ibm-management-ingress-operator.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.1/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
  pkg/controller/managementingress/handler/cert.go
  pkg/controller/managementingress/handler/configmap.go
  version/version.go
Labels: lgtm, needs-ok-to-test, size/XL

#80 Create CSV version 1.3.0 for roadmap development
  Makefile
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.0/ibm-management-ingress-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
  version/version.go
Labels: size/XL

#81 Remove required image field in deploy/CRD to pass ibm certification
  deploy/crds/operator.ibm.com_managementingresses_crd.yaml
Labels: size/XS

#82 update CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  RELEASE.md
  docs/dev/development.md
  docs/dev/e2e.md
  docs/install/install.md
Labels: size/M
