Repository IBM/ibm-management-ingress-operator, pull requests merged in 2020-08, with the labels that each got.

#87 change cicd pipeline
  Makefile
  common/scripts/config_docker.sh
Labels: size/S

#88 update multiarch image version
  common/scripts/multiarch_image.sh
Labels: size/XS

#89 fix typo
  common/scripts/multiarch_image.sh
Labels: size/XS

#91 add podAntiAffinity.
  pkg/controller/managementingress/handler/deployment.go
  pkg/controller/managementingress/handler/ingressrequest.go
Labels: size/M

#92 Update csv to use latest operand image
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.0/ibm-management-ingress-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#95 update operand image digest
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.0/ibm-management-ingress-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS
