Repository IBM/ibm-management-ingress-operator, pull requests merged in 2020-11, with the labels that each got.

#137 Wait for cert manager and router secret
  controllers/handler/cert.go
  controllers/handler/deployment.go
  controllers/handler/ingressrequest.go
  controllers/handler/route.go
  controllers/managementingress_controller.go
Labels: approved, size/L

#138 Update cp-console route when certificate was renewed
  controllers/handler/route.go
Labels: approved, size/M

#139 support namespace scope operator.
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  controllers/handler/constants.go
  controllers/handler/deployment.go
  controllers/handler/ingressrequest.go
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/ibm-management-ingress-operator.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#140 update operand image digest.
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/ibm-management-ingress-operator.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#141 Update operand image digest to unblock build
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
Labels: approved, size/XS

#142 fix certificate update issue for operator upgrade.
  api/v1alpha1/managementingress_types.go
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_managementingresses.yaml
  config/crd/bases/operator.ibm.com_managementingresses.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  controllers/handler/cert.go
  controllers/handler/constants.go
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/ibm-management-ingress-operator.v1.4.0.clusterserviceversion.yaml
Labels: approved, do-not-merge/hold, size/L

#143 fix upgrade issue
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/ibm-management-ingress-operator.v1.4.0.clusterserviceversion.yaml
  utils/utils.go
Labels: approved, lgtm, size/M

#144 update check difference.
  controllers/handler/cert.go
  controllers/handler/configmap.go
  controllers/handler/deployment.go
  controllers/handler/route.go
  utils/utils.go
Labels: approved, lgtm, size/M

#145 update check difference
  controllers/handler/deployment.go
  controllers/handler/service.go
  utils/utils.go
Labels: approved, lgtm, size/L

#146 sync crd to legacy dir.
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/operator.ibm.com_managementingresses_crd.yaml
Labels: approved, lgtm, size/M

#147 update base image.
  build/Dockerfile
Labels: approved, lgtm, size/XS

#148 update operand image digest.
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/ibm-management-ingress-operator.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#149 fix incorrect configmap name.
  controllers/handler/deployment.go
Labels: approved, lgtm, size/XS

#150 double verify multiarch image manifest creation.
  Makefile
  common/scripts/multiarch_image.sh
Labels: approved, lgtm, size/S

#152 fix multiarch image manifests.
  Makefile
Labels: approved, lgtm, size/XS

#153 fix multiarch image manifests.
  Makefile
Labels: approved, lgtm, size/XS

#154 add deploy manifests for case bundle tests.
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
Labels: approved, lgtm, size/L

#155 disable leader election.
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.1/ibm-management-ingress-operator.v1.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#156 update operand image digest.
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.1/ibm-management-ingress-operator.v1.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#158 update operand image digest.
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.2/ibm-management-ingress-operator.v1.4.2.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#159 Add null check when compare Resources
  utils/resources.go
Labels: approved, lgtm, size/S

#160 Ingore labels of deployment when check the difference
  utils/utils.go
Labels: approved, lgtm, size/XS

#161 Still need to compare labels to get deployment update
  utils/utils.go
Labels: approved, lgtm, size/S
