Repository IBM/ibm-management-ingress-operator, pull requests merged in 2020-04, with the labels that each got.

#22 add license
  Makefile
  cmd/manager/main.go
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/operator/group.go
  pkg/apis/operator/v1alpha1/doc.go
  pkg/apis/operator/v1alpha1/managementingress_types.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_managementingress.go
  pkg/controller/controller.go
  pkg/controller/managementingress/handler/Ingressrequest_test.go
  pkg/controller/managementingress/handler/cert.go
  pkg/controller/managementingress/handler/cert_test.go
  pkg/controller/managementingress/handler/configmap.go
  pkg/controller/managementingress/handler/configmap_test.go
  pkg/controller/managementingress/handler/constants.go
  pkg/controller/managementingress/handler/default.go
  pkg/controller/managementingress/handler/deployment.go
  pkg/controller/managementingress/handler/deployment_test.go
  pkg/controller/managementingress/handler/ingressrequest.go
  pkg/controller/managementingress/handler/rbac.go
  pkg/controller/managementingress/handler/reconciler.go
  pkg/controller/managementingress/handler/reconciler_test.go
  pkg/controller/managementingress/handler/route.go
  pkg/controller/managementingress/handler/route_test.go
  pkg/controller/managementingress/handler/scc.go
  pkg/controller/managementingress/handler/service.go
  pkg/controller/managementingress/handler/service_test.go
  pkg/controller/managementingress/handler/serviceaccount.go
  pkg/controller/managementingress/handler/serviceaccount_test.go
  pkg/controller/managementingress/managementingress_controller.go
  pkg/utils/resources.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  tools.go
  version/version.go
Labels: size/XL

#23 build multiarch image
  Makefile
  common/scripts/multiarch_image.sh
Labels: size/M

#25 modify operator configurations to pass IBM certification
  Makefile
  README.md
  deploy/clusterrole.yaml
  deploy/clusterrole_binding.yaml
  deploy/crds/operator.ibm.com_managementingresses_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_managementingress_cr.yaml
  deploy/namespace.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.1.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/operand_request.yaml
  deploy/operator.yaml
  deploy/service_account.yaml
Labels: size/M

#26 add lables
  deploy/operator.yaml
Labels: size/XS

#27 redhat certification configurations
  .osdk-scorecard.yaml
  deploy/olm-catalog/csv-config.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.1.0/ibm-management-ingress-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operand_request.yaml
Labels: size/L

#28 remove type object
  deploy/crds/operator.ibm.com_managementingresses_crd.yaml
Labels: size/XS

#29 delete csv
  deploy/olm-catalog/csv-config.yaml
Labels: size/XS

#30 update healcheck
  deploy/operator.yaml
Labels: size/S

#31 add health check script
  build/build.sh
  deploy/operator.yaml
Labels: size/S

#32 rename health check script
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  build/health_check.sh
Labels: size/XS

#33 modify health check command
  deploy/operator.yaml
Labels: size/XS

#34 update version for cicd
  version/version.go
Labels: size/XS

#35 add role and rolebinding to pass IBM certify test case
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: size/L

#24 Change priority of scc to the lowest
  pkg/controller/managementingress/handler/scc.go
Labels: needs-ok-to-test, size/XS

#37 update Makefile target to push multiarch images
  Makefile
Labels: size/XS

#38 update git version
  Makefile
  git
Labels: size/XS

#39 update cvs version
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
  version/version.go
Labels: size/XL

#36 add operator dependency
  deploy/olm-catalog/ibm-management-ingress-operator/1.1.0/ibm-management-ingress-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
Labels: size/M

#41 update operator tag
  Makefile
  common/scripts/multiarch_image.sh
Labels: size/XS

#43 push 1.2.0 image
  common/scripts/multiarch_image.sh
Labels: size/XS

#44 update image version
  Makefile
Labels: size/XS

#45 update memory limit
  deploy/olm-catalog/ibm-management-ingress-operator/1.1.0/ibm-management-ingress-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
  pkg/controller/managementingress/handler/default.go
Labels: size/S

#46 update push csv script
  common/scripts/push-csv.sh
Labels: size/M

#48 add replace version
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
Labels: size/XS

#49 rebase the image version
  Makefile
  common/scripts/multiarch_image.sh
Labels: size/XS

#51 update ubi base image
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/XS
