Repository IBM/ibm-management-ingress-operator, pull requests merged in 2020-05, with the labels that each got.

#54 Revert "add api v1"
  .osdk-scorecard.yaml
  Makefile
  common/Makefile.common.mk
  deploy/crds/operator.ibm.com_managementingresses_crd.yaml
  deploy/crds/operator.ibm.com_v1_managementingress_cr.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/operator.ibm.com_managementingresses_crd.yaml
  pkg/apis/addtoscheme_operator_v1.go
  pkg/apis/operator/v1/doc.go
  pkg/apis/operator/v1/managementingress_types.go
  pkg/apis/operator/v1/register.go
  pkg/apis/operator/v1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/managementingress/handler/cert.go
  pkg/controller/managementingress/handler/ingressrequest.go
  pkg/controller/managementingress/handler/reconciler.go
  pkg/controller/managementingress/managementingress_controller.go
  pkg/utils/utils.go
  test/e2e/managementingressoperatorset_test.go
  test/helpers/helpers.go
Labels: size/XL

#55 use image digest for operand image
  deploy/operator.yaml
  pkg/controller/managementingress/handler/deployment.go
Labels: size/S

#56 use image digest for operand image
  deploy/olm-catalog/ibm-management-ingress-operator/1.1.0/ibm-management-ingress-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
  pkg/controller/managementingress/handler/deployment.go
Labels: size/XS

#57 Merge branch 'master' into use-image-digest
  deploy/olm-catalog/ibm-management-ingress-operator/1.1.0/ibm-management-ingress-operator.v1.1.0.clusterserviceversion.yaml
  pkg/controller/managementingress/handler/deployment.go
Labels: size/XS

#58 update ubi image
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/XS

#53 Added ibm-cloud-info configmap
  README.md
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/managementingress/handler/configmap.go
  pkg/controller/managementingress/handler/constants.go
  pkg/controller/managementingress/handler/route.go
Labels: size/L

#60 Remove extra braces for OperandBindInfo.
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
Labels: size/XS

#61 upgrade operand image to 2.5.2
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
Labels: size/XS

#62 add image tag
  common/scripts/multiarch_image.sh
Labels: size/XS

#64 update csv
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
Labels: size/XS

#65 image with digest
  deploy/crds/operator.ibm.com_v1alpha1_managementingress_cr.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/managementingress_types.go
  pkg/controller/managementingress/handler/deployment.go
Labels: size/M

#67 update cs version
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/managementingress/handler/constants.go
Labels: size/XS

#66 Added api server info in configmap ibmcloud-cluster-info.
  go.mod
  pkg/controller/managementingress/handler/configmap.go
  pkg/controller/managementingress/handler/constants.go
  pkg/controller/managementingress/handler/ingressrequest.go
Labels: size/L

#68 Added ownerReference for configmap ibmcloud-cluster-info when patching.
  pkg/controller/managementingress/handler/configmap.go
Labels: size/XS

#69 push latest image
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
Labels: size/XS

#71 Remove prefix https:// from api server address.
  pkg/controller/managementingress/handler/configmap.go
Labels: size/XS

#73 Create beta channel for Common Service 2020 2Q release
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
Labels: needs-ok-to-test, size/S

#72 update readme file
  README.md
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
Labels: size/L

#74 Create version 1.2.1 for bug fix of release 1.2
  Makefile
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.1/ibm-management-ingress-operator.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.1/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
  version/version.go
Labels: needs-ok-to-test, size/XL

#75 Add key usage for certificate used by management ingress
  pkg/controller/managementingress/handler/cert.go
Labels: needs-ok-to-test, size/XS

#76 Fix issue routeHost is not working as expected
  pkg/controller/managementingress/handler/configmap.go
Labels: needs-ok-to-test, size/XS
