Repository IBM/ibm-management-ingress-operator, pull requests merged in 2020-09, with the labels that each got.

#98 create new csv version 1.3.1
  Makefile
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
  version/version.go
Labels: size/XL

#99 Add labels to support power and s390x
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
Labels: size/XS

#101 upate base image
  build/Dockerfile
  build/Dockerfile.ppc64le
Labels: size/XS

#102 change dev channel version
  deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
Labels: size/XS

#103 update base image
  build/Dockerfile.ppc64le
Labels: size/XS

#104 update build makefile to use real-multiarch build.
  Makefile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/L

#106 fix arch.
  Makefile
Labels: size/S

#108 remove duplicated field
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
Labels: size/S

#109 remove-duplicated-field
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
Labels: size/XS

#110 remove metering product version
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/managementingress/handler/constants.go
  pkg/controller/managementingress/handler/ingressrequest.go
Labels: size/XS

#111 upadte base image
  build/Dockerfile
Labels: size/XS

#112 Clean up cluster resource in finalizer
  deploy/crds/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/operator.ibm.com_managementingresses_crd.yaml
  pkg/controller/managementingress/handler/cert.go
  pkg/controller/managementingress/handler/configmap.go
  pkg/controller/managementingress/handler/constants.go
  pkg/controller/managementingress/handler/default.go
  pkg/controller/managementingress/handler/deployment.go
  pkg/controller/managementingress/handler/ingressrequest.go
  pkg/controller/managementingress/handler/rbac.go
  pkg/controller/managementingress/handler/reconciler.go
  pkg/controller/managementingress/handler/route.go
  pkg/controller/managementingress/handler/scc.go
  pkg/controller/managementingress/handler/service.go
  pkg/controller/managementingress/handler/serviceaccount.go
  pkg/controller/managementingress/managementingress_controller.go
  pkg/utils/utils.go
Labels: size/XL

#113 fix multiarch image version issue.
  Makefile
  common/scripts/multiarch_image.sh
Labels: size/M

#114 Have correct configmap name in the event
  pkg/controller/managementingress/handler/configmap.go
Labels: size/XS

#116 Use soft podAntiAffinity policy instead of hard
  pkg/controller/managementingress/handler/deployment.go
Labels: size/S

#117 update image digest
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/XS

#118 Bump operator version to 1.3.2
  Makefile
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.2/ibm-management-ingress-operator.v1.3.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.2/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
  version/version.go
Labels: size/XL

#119 Watch managed resources
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.3/ibm-management-ingress-operator.v1.3.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.3/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
  pkg/controller/managementingress/handler/configmap.go
  pkg/controller/managementingress/handler/reconciler.go
  pkg/controller/managementingress/handler/route.go
  pkg/controller/managementingress/managementingress_controller.go
  version/version.go
Labels: size/XL
