Repository IBM/ibm-management-ingress-operator, pull requests merged in 2021-11, with the labels that each got.

#226 Opt-in for auto update of SHA value for operand
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS

#231 update version
  version/version.go
Labels: approved

#232 remove nodeport from cluster-info configmap
  controllers/handler/configmap.go
  controllers/handler/constants.go
Labels: size/XS, approved

#233 Update script
  common/scripts/bump-up-csv.sh
Labels: approved

#234 Changes for RH mirroring
  deploy/olm-catalog/ibm-management-ingress-operator/1.11.0/ibm-management-ingress-operator.v1.11.0.clusterserviceversion.yaml
Labels: size/XS

#235 Changes for RH mirroring for EUS branch.
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.5/ibm-management-ingress-operator.v1.4.5.clusterserviceversion.yaml
Labels: lgtm, size/XS

#236 fix 50956
  controllers/handler/deployment.go
Labels: size/M, approved

#237 Add k functionality
  common/scripts/multiarch_image.sh
  controllers/handler/common.go
  controllers/handler/configmap.go
  controllers/handler/constants.go
  controllers/handler/deployment.go
  controllers/handler/reconciler.go
  controllers/managementingress_controller.go
  main.go
Labels: size/L
