Repository IBM/ibm-management-ingress-operator, pull requests merged in 2021-01, with the labels that each got.

#166 only update the data field of the configmap
  controllers/handler/configmap.go
Labels: lgtm, size/XS

#167 add rcsherro as owner
  OWNERS
Labels: size/XS

#169 support v3 channel and fix package vulnerability
  build/Dockerfile
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.5.0/ibm-management-ingress-operator.v1.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S
