Repository IBM/ibm-management-ingress-operator, pull requests merged in 2021-04, with the labels that each got.

#180 change image tag for multiarch
  Makefile
Labels: size/XS

#181 add operator fixes from CS 3.7 and fix PSIRT
  api/v1alpha1/managementingress_types.go
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_managementingresses.yaml
  common/scripts/bump-up-csv.sh
  config/crd/bases/operator.ibm.com_managementingresses.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/rbac/role_binding.yaml
  controllers/handler/cert.go
  controllers/handler/configmap.go
  controllers/handler/deployment.go
  controllers/handler/reconciler.go
  controllers/handler/route.go
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.4/ibm-management-ingress-operator.v1.4.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.4/operator.ibm.com_managementingresses_crd.yaml
  go.mod
  go.sum
Labels: size/L

#182 remove myself from OWNERS file.
  OWNERS
Labels: approved, lgtm, size/XS

#183 update UBI image and operand SHA
  build/Dockerfile
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.4/ibm-management-ingress-operator.v1.4.4.clusterserviceversion.yaml
Labels: size/S
