Repository IBM/ibm-management-ingress-operator, pull requests merged in 2022-04, with the labels that each got.

#250 version bump april
  README.md
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.1.0/ibm-management-ingress-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.1.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.10.0/ibm-management-ingress-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.10.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.11.0/ibm-management-ingress-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.11.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.12.0/ibm-management-ingress-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.12.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.13.0/ibm-management-ingress-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.13.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.14.0/ibm-management-ingress-operator.v1.14.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.14.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.1/ibm-management-ingress-operator.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.2.1/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.0/ibm-management-ingress-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.2/ibm-management-ingress-operator.v1.3.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.2/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.3/ibm-management-ingress-operator.v1.3.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.3.3/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/ibm-management-ingress-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.1/ibm-management-ingress-operator.v1.4.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.1/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.2/ibm-management-ingress-operator.v1.4.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.4.2/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.5.0/ibm-management-ingress-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.5.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.5.1/ibm-management-ingress-operator.v1.5.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.5.1/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.6.0/ibm-management-ingress-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.6.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.7.0/ibm-management-ingress-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.7.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.7.1/ibm-management-ingress-operator.v1.7.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.7.1/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.8.0/ibm-management-ingress-operator.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.8.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.9.0/ibm-management-ingress-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/1.9.0/operator.ibm.com_managementingresses_crd.yaml
  deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
  version/version.go
Labels: size/XXL, lgtm, approved

#251 remove replaces csv keyword for LTSR
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#252 fix version change
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#253 updates for cv linting fixes
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  controllers/handler/reconciler.go
Labels: lgtm, size/M, approved

#254 add liveness and readiness probes to operator
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  main.go
Labels: lgtm, size/M, approved

#255 fix probe definition
  config/manager/manager.yaml
  main.go
Labels: lgtm, size/M, approved

#256 config/manager/manager.yaml
  config/manager/manager.yaml
Labels: lgtm, size/XS, approved

#257 update security context
  controllers/handler/deployment.go
Labels: size/S, lgtm, approved

#258 update image refs to be icr.io
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/samples/operator_v1alpha1_managementingress.yaml
Labels: lgtm, size/M, approved
