Repository IBM/ibm-management-ingress-operator, pull requests merged in 2023-07, with the labels that each got.

#312 cicd version bump automation for pipelines/CS-ltsr.json
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S, lgtm, approved

#313 fix upgrade issue by deleting deployment
  controllers/handler/reconciler.go
  controllers/managementingress_controller.go
Labels: size/M, approved

#314 update controller and kube for twistlock
  controllers/handler/deployment.go
  controllers/handler/ingressrequest.go
  controllers/managementingress_controller.go
  go.mod
  go.sum
Labels: size/XL, approved

#315 add prems for lease object
  bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
Labels: size/S, approved
